myGeneData <- list()
myGeneData[["A2ML1"]] <- structure(list(sym = "A2ML1",
                                        name = "alpha-2-macroglobulin like 1",
                                        UniProt = "A8K2U0", RefSeq = "NM_144670", assembly = "GRCh38",
                                        chr = 12L, strand = "+", geneStart = 8822472L, geneEnd = 8887001L,
                                        cdsStarts = c(8822652L, 8823182L, 8823720L, 8829727L, 8834662L,
                                                      8835507L, 8836255L, 8837440L, 8838336L, 8839113L, 8841369L,
                                                      8843134L, 8845442L, 8846077L, 8847549L, 8848720L, 8849669L,
                                                      8850160L, 8851784L, 8852210L, 8854128L, 8854780L, 8855509L,
                                                      8857164L, 8857507L, 8857946L, 8860881L, 8861135L, 8863794L,
                                                      8867842L, 8868230L, 8868537L, 8869135L, 8874425L, 8874971L,
                                                      NA), cdsEnds = c(8822713L, 8823365L, 8823882L, 8829779L,
                                                                       8834682L, 8835666L, 8836339L, 8837566L, 8838450L, 8839222L,
                                                                       8841536L, 8843361L, 8845502L, 8846222L, 8847698L, 8848914L,
                                                                       8849759L, 8850274L, 8852012L, 8852336L, 8854249L, 8854831L,
                                                                       8855592L, 8857340L, 8857588L, 8858102L, 8860955L, 8861297L,
                                                                       8864008L, 8868057L, 8868357L, 8868627L, 8869203L, 8874527L,
                                                                       8875011L, NA), map = NULL, cds = paste0(
                                                                           "ATGTGGGCTCAGCTCCTTCTAGGAATGTTGGCCCTATCACCAGCCATTGCAGAAGAACTTCCA",
                                                                           "AACTACCTGGTGACATTACCAGCCCGGCTAAATTTCCCCTCCGTTCAGAAGGTTTGTTTGGAC",
                                                                           "CTGAGCCCTGGGTACAGTGATGTTAAATTCACGGTTACTCTGGAGACCAAGGACAAGACCCAG",
                                                                           "AAGTTGCTAGAATACTCTGGACTGAAGAAGAGGCACTTACATTGTATCTCCTTTCTTGTACCA",
                                                                           "CCTCCTGCTGGTGGCACAGAAGAAGTGGCCACAATCCGGGTGTCGGGAGTTGGAAATAACATC",
                                                                           "AGCTTTGAGGAGAAGAAAAAGGTTCTAATTCAGAGGCAGGGGAACGGCACCTTTGTACAGACT",
                                                                           "GACAAACCTCTCTACACCCCAGGGCAGCAAGTGTATTTCCGCATTGTCACCATGGATAGCAAC",
                                                                           "TTCGTTCCAGTGAATGACAAGTACTCCATGGTGGAACTACAGGATCCAAATAGCAACAGGATT",
                                                                           "GCACAGTGGCTGGAAGTGGTACCTGAGCAAGGCATTGTAGACCTGTCCTTCCAACTGGCACCA",
                                                                           "GAGGCAATGCTGGGCACCTACACTGTGGCAGTGGCTGAGGGCAAGACCTTTGGTACTTTCAGT",
                                                                           "GTGGAGGAATATGTGCTGCCGAAGTTTAAGGTGGAAGTGGTGGAACCCAAGGAGTTATCAACG",
                                                                           "GTGCAGGAATCTTTCTTAGTAAAAATTTGTTGTAGGTACACCTATGGAAAGCCCATGCTAGGG",
                                                                           "GCAGTGCAGGTATCTGTGTGTCAGAAGGCAAATACTTACTGGTATCGAGAGGTGGAACGGGAA",
                                                                           "CAGCTTCCTGACAAATGCAGGAACCTCTCTGGACAGACTGACAAAACAGGATGTTTCTCAGCA",
                                                                           "CCTGTGGACATGGCCACCTTTGACCTCATTGGATATGCGTACAGCCATCAAATCAATATTGTG",
                                                                           "GCTACTGTTGTGGAGGAAGGGACAGGTGTGGAGGCCAATGCCACTCAGAATATCTACATTTCT",
                                                                           "CCACAAATGGGATCAATGACCTTTGAAGACACCAGCAATTTTTACCATCCAAATTTCCCCTTC",
                                                                           "AGTGGGAAGATAAGAGTTAGGGGCCATGATGACTCCTTCCTCAAGAACCATCTAGTGTTTCTG",
                                                                           "GTGATTTATGGCACAAATGGAACCTTCAACCAGACCCTGGTTACTGATAACAATGGCCTAGCT",
                                                                           "CCCTTTACCTTGGAGACATCCGGTTGGAATGGGACAGACGTTTCTCTGGAGGGAAAGTTTCAA",
                                                                           "ATGGAAGACTTAGTATATAATCCGGAACAAGTGCCACGTTACTACCAAAATGCCTACCTGCAC",
                                                                           "CTGCGACCCTTCTACAGCACAACCCGCAGCTTCCTTGGCATCCACCGGCTAAACGGCCCCTTG",
                                                                           "AAATGTGGCCAGCCCCAGGAAGTGCTGGTGGATTATTACATCGACCCGGCCGATGCAAGCCCT",
                                                                           "GACCAAGAGATCAGCTTCTCCTACTATTTAATAGGGAAAGGAAGTTTGGTGATGGAGGGGCAG",
                                                                           "AAACACCTGAACTCTAAGAAGAAAGGACTGAAAGCCTCCTTCTCTCTCTCACTGACCTTCACT",
                                                                           "TCGAGACTGGCCCCTGATCCTTCCCTGGTGATCTATGCCATTTTTCCCAGTGGAGGTGTTGTA",
                                                                           "GCTGACAAAATTCAGTTCTCAGTCGAGATGTGCTTTGACAATCAGGTTTCCCTTGGCTTCTCC",
                                                                           "CCCTCCCAGCAGCTTCCAGGAGCAGAAGTGGAGCTGCAGCTGCAGGCAGCTCCCGGATCCCTG",
                                                                           "TGTGCGCTCCGGGCGGTGGATGAGAGTGTCTTACTGCTTAGGCCAGACAGAGAGCTGAGCAAC",
                                                                           "CGCTCTGTCTATGGGATGTTTCCATTCTGGTATGGTCACTACCCCTATCAAGTGGCTGAGTAT",
                                                                           "GATCAGTGTCCAGTGTCTGGCCCATGGGACTTTCCTCAGCCCCTCATTGACCCAATGCCCCAA",
                                                                           "GGGCATTCGAGCCAGCGTTCCATTATCTGGAGGCCCTCGTTCTCTGAAGGCACGGACCTTTTC",
                                                                           "AGCTTTTTCCGGGACGTGGGCCTGAAAATACTGTCCAATGCCAAAATCAAGAAGCCAGTAGAT",
                                                                           "TGCAGTCACAGATCTCCAGAATACAGCACTGCTATGGGTGCAGGCGGTGGTCATCCAGAGGCT",
                                                                           "TTTGAGTCATCAACTCCTTTACATCAAGCAGAGGATTCTCAGGTCCGCCAGTACTTCCCAGAG",
                                                                           "ACCTGGCTCTGGGATCTGTTTCCTATTGGTAACTCGGGGAAGGAGGCGGTCCACGTCACAGTT",
                                                                           "CCTGACGCCATCACCGAGTGGAAGGCGATGAGTTTCTGCACTTCCCAGTCAAGAGGCTTCGGG",
                                                                           "CTTTCACCCACTGTTGGACTAACTGCTTTCAAGCCGTTCTTTGTTGACCTGACTCTCCCTTAC",
                                                                           "TCAGTAGTCCGTGGGGAATCCTTTCGTCTTACTGCCACCATCTTCAATTACCTAAAGGATTGC",
                                                                           "ATCAGGGTTCAGACTGACCTGGCTAAATCGCATGAGTACCAGCTAGAATCATGGGCAGATTCT",
                                                                           "CAGACCTCCAGTTGTCTCTGTGCTGATGACGCAAAAACCCACCACTGGAACATCACAGCTGTC",
                                                                           "AAATTGGGTCACATTAACTTTACTATTAGTACAAAGATTCTGGACAGCAATGAACCATGTGGG",
                                                                           "GGCCAGAAGGGGTTTGTTCCCCAAAAGGGCCGAAGTGACACGCTCATCAAGCCAGTTCTCGTC",
                                                                           "AAACCTGAGGGAGTCCTGGTGGAGAAGACACACAGCTCATTGCTGTGCCCAAAAGGAAAGGTG",
                                                                           "GCATCTGAATCTGTCTCCCTGGAGCTCCCAGTGGACATTGTTCCTGACTCGACCAAGGCTTAT",
                                                                           "GTTACGGTTCTGGGAGACATTATGGGCACAGCCCTGCAGAACCTGGATGGTCTGGTGCAGATG",
                                                                           "CCCAGTGGCTGTGGCGAGCAGAACATGGTCTTGTTTGCTCCCATCATCTATGTCTTGCAGTAC",
                                                                           "CTGGAGAAGGCAGGGCTGCTGACGGAGGAGATCAGGTCTCGGGCAGTGGGTTTCCTGGAAATA",
                                                                           "GGGTACCAGAAGGAGCTGATGTACAAACACAGCAATGGCTCATACAGTGCCTTTGGGGAGCGA",
                                                                           "GATGGAAATGGAAACACATGGCTGACAGCGTTTGTCACAAAATGCTTTGGCCAAGCTCAGAAA",
                                                                           "TTCATCTTCATTGATCCCAAGAACATCCAGGATGCTCTCAAGTGGATGGCAGGAAACCAGCTC",
                                                                           "CCCAGTGGCTGCTATGCCAACGTGGGAAATCTCCTTCACACAGCTATGAAGGGTGGTGTTGAT",
                                                                           "GATGAGGTCTCCTTGACTGCGTATGTCACAGCTGCATTGCTGGAGATGGGAAAGGATGTAGAT",
                                                                           "GACCCAATGGTGAGTCAGGGTCTACGGTGTCTCAAGAATTCGGCCACCTCCACGACCAACCTC",
                                                                           "TACACACAGGCCCTGTTGGCTTACATTTTCTCCCTGGCTGGGGAAATGGACATCAGAAACATT",
                                                                           "CTCCTTAAACAGTTAGATCAACAGGCTATCATCTCAGGAGAATCCATTTACTGGAGCCAGAAA",
                                                                           "CCTACTCCATCATCGAACGCCAGCCCTTGGTCTGAGCCTGCGGCTGTAGATGTGGAACTCACA",
                                                                           "GCATATGCATTGTTGGCCCAGCTTACCAAGCCCAGCCTGACTCAAAAGGAGATAGCGAAGGCC",
                                                                           "ACTAGCATAGTGGCTTGGTTGGCCAAGCAACACAATGCATATGGGGGCTTCTCTTCTACTCAG",
                                                                           "GATACTGTAGTTGCTCTCCAAGCTCTTGCCAAATATGCCACTACCGCCTACATGCCATCTGAG",
                                                                           "GAGATCAACCTGGTTGTAAAATCCACTGAGAATTTCCAGCGCACATTCAACATACAGTCAGTT",
                                                                           "AACAGATTGGTATTTCAGCAGGATACCCTGCCCAATGTCCCTGGAATGTACACGTTGGAGGCC",
                                                                           "TCAGGCCAGGGCTGTGTCTATGTGCAGACGGTGTTGAGATACAATATTCTCCCTCCCACAAAT",
                                                                           "ATGAAGACCTTTAGTCTTAGTGTGGAAATAGGAAAAGCTAGATGTGAGCAACCGACTTCACCT",
                                                                           "CGATCCTTGACTCTCACTATTCACACCAGTTATGTGGGGAGCCGTAGCTCTTCCAATATGGCT",
                                                                           "ATTGTGGAAGTGAAGATGCTATCTGGGTTCAGTCCCATGGAGGGCACCAATCAGTTACTTCTC",
                                                                           "CAGCAACCCCTGGTGAAGAAGGTTGAATTTGGAACTGACACACTTAACATTTACTTGGATGAG",
                                                                           "CTCATTAAGAACACTCAGACTTACACCTTCACCATCAGCCAAAGTGTGCTGGTCACCAACTTG",
                                                                           "AAACCAGCAACCATCAAGGTCTATGACTACTACCTACCAGATGAACAGGCAACAATTCAGTAT",
                                                                           "TCTGATCCCTGTGAATGA"),
                                        phastCons = NULL, phyloP = NULL, xyzMap = NULL, xyz = NULL),
                                   .Names = c("sym",
                                              "name", "UniProt", "RefSeq", "assembly", "chr", "strand", "geneStart",
                                              "geneEnd", "cdsStarts", "cdsEnds", "map", "cds", "phastCons",
                                              "phyloP", "xyzMap", "xyz"))

myGeneData[["A1BG"]] <- structure(list(sym = "A1BG",
                                       name = "alpha-1-B glycoprotein",
                                       UniProt = "P04217", RefSeq = "NM_130786", assembly = "GRCh38",
                                       chr = 19L, strand = "-", geneStart = 58345178L, geneEnd = 58353499L,
                                       cdsStarts = c(58353404L, 58353292L, 58352928L, 58352283L,
                                                     58351391L, 58350370L, 58347353L, 58347022L), cdsEnds = c(58353437L,
                                                                                                              58353327L, 58353197L, 58352555L, 58351687L, 58350651L, 58347640L,
                                                                                                              58347029L), map = NULL, cds = paste0(
                                                                                                                  "ATGTCCATGCTCGTGGTCTTTCTCTTGCTGTGGGGTGTCACCTGGGGCCCAGTG",
                                                                                                                  "ACAGAAGCAGCCATATTTTATGAGACGCAGCCCAGCCTGTGGGCAGAGTCCGAAT",
                                                                                                                  "CACTGCTGAAACCCTTGGCCAATGTGACGCTGACGTGCCAGGCCCACCTGGAGAC",
                                                                                                                  "TCCAGACTTCCAGCTGTTCAAGAATGGGGTGGCCCAGGAGCCTGTGCACCTTGAC",
                                                                                                                  "TCACCTGCCATCAAGCACCAGTTCCTGCTGACGGGTGACACCCAGGGCCGCTACC",
                                                                                                                  "GCTGCCGCTCGGGCTTGTCCACAGGATGGACCCAGCTGAGCAAGCTCCTGGAGCT",
                                                                                                                  "GACAGGGCCAAAGTCCTTGCCTGCTCCCTGGCTCTCGATGGCGCCAGTGTCCTGG",
                                                                                                                  "ATCACCCCCGGCCTGAAAACAACAGCAGTGTGCCGAGGTGTGCTGCGGGGTGTGA",
                                                                                                                  "CTTTTCTGCTGAGGCGGGAGGGCGACCATGAGTTTCTGGAGGTGCCTGAGGCCCA",
                                                                                                                  "GGAGGATGTGGAGGCCACCTTTCCAGTCCATCAGCCTGGCAACTACAGCTGCAGC",
                                                                                                                  "TACCGGACCGATGGGGAAGGCGCCCTCTCTGAGCCCAGCGCTACTGTGACCATTG",
                                                                                                                  "AGGAGCTCGCTGCACCACCACCGCCTGTGCTGATGCACCATGGAGAGTCCTCCCA",
                                                                                                                  "GGTCCTGCACCCTGGCAACAAGGTGACCCTCACCTGCGTGGCTCCCCTGAGTGGA",
                                                                                                                  "GTGGACTTCCAGCTACGGCGCGGGGAGAAAGAGCTGCTGGTACCCAGGAGCAGCA",
                                                                                                                  "CCAGCCCAGATCGCATCTTCTTTCACCTGAACGCGGTGGCCCTGGGGGATGGAGG",
                                                                                                                  "TCACTACACCTGCCGCTACCGGCTGCATGACAACCAAAACGGCTGGTCCGGGGAC",
                                                                                                                  "AGCGCGCCGGTCGAGCTGATTCTGAGCGATGAGACGCTGCCCGCGCCGGAGTTCT",
                                                                                                                  "CCCCGGAGCCGGAGTCCGGCAGGGCCTTGCGGCTGCGGTGCCTGGCGCCCCTGGA",
                                                                                                                  "GGGCGCGCGCTTCGCCCTGGTGCGCGAGGACAGGGGCGGGCGCCGCGTGCACCGT",
                                                                                                                  "TTCCAGAGCCCCGCTGGGACCGAGGCGCTCTTCGAGCTGCACAACATTTCCGTGG",
                                                                                                                  "CTGACTCCGCCAACTACAGCTGCGTCTACGTGGACCTGAAGCCGCCTTTCGGGGG",
                                                                                                                  "CTCCGCGCCCAGCGAGCGCTTGGAGCTGCACGTGGACGGACCCCCTCCCAGGCCT",
                                                                                                                  "CAGCTCCGGGCGACGTGGAGTGGGGCGGTCCTGGCGGGCCGAGATGCCGTCCTGC",
                                                                                                                  "GCTGCGAGGGACCCATCCCCGACGTCACCTTCGAGCTGCTGCGCGAGGGCGAGAC",
                                                                                                                  "GAAGGCCGTGAAGACGGTCCGCACCCCCGGGGCCGCGGCGAACCTCGAGCTGATC",
                                                                                                                  "TTCGTGGGGCCCCAGCACGCCGGCAACTACAGGTGCCGCTACCGCTCCTGGGTGC",
                                                                                                                  "CCCACACCTTCGAATCGGAGCTCAGCGACCCTGTGGAGCTCCTGGTGGCAGAAAGCTGA"),
                                       phastCons = NULL, phyloP = NULL, xyzMap = NULL, xyz = NULL),
                                  .Names = c("sym",
                                             "name", "UniProt", "RefSeq", "assembly", "chr", "strand", "geneStart",
                                             "geneEnd", "cdsStarts", "cdsEnds", "map", "cds", "phastCons",
                                             "phyloP", "xyzMap", "xyz"))
